# Generated by Django 5.0 on 2024-11-05 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CohortGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_join', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Program', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.URLField(max_length=500, verbose_name='Profile Image URL')),
                ('full_name', models.CharField(max_length=100)),
                ('cohort', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date_joined', models.DateField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('date_join', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='student_profile')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cohorts.student')),
            ],
        ),
    ]
